### ISSUE TITLE
Audit the reentrancy settings

### ISSUE THREAD

**Issue by pbirkhol-ni** [ni/measurement-plugin-labview#160]
# Bug Report

Some VIs need to be reentrant for parallel test. For example, Measurement Logic.vi should be reentrant but is currently set to non-reentrant. We need to audit all of the VIs (examples, discovery client, session manager, template VIs, etc) to make sure that the reentrancy settings make sense.

[AB#2278720](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2278720)

**Comment by dixonjoel** [comment]
Over time, we've reviewed the reentrancy settings. We don't have any immediate plans to change these so closing.
