### ISSUE TITLE
Non-ASCII chars render incorrectly when dynamically registered.

### ISSUE THREAD

**Issue by cumitche** [ni/measurement-plugin-labview#249]
# Bug Report

Characters beyond ASCII are not rendering correctly when a service is dynamically registered.

## Repro or Code Sample

Use the generator to create a measurement service that has accented characters in its name and/or description.

## Expected Behavior

The service name and description show up correctly.  This following image is taken from a statically registered service.
![image](https://github.com/ni/measurementlink-labview/assets/77293599/bf9814a2-b20c-4d7f-ad5d-430a4d54b45c)

## Current Behavior

The non-ASCII characters are rendered as a ? in a black diamond in InstrumentStudio when the service is dynamically registered.
![image](https://github.com/ni/measurementlink-labview/assets/77293599/34321e32-c823-47f3-bc56-f5c13bfd51c9)

## Your Environment

* OS & Device: Windows, 10 on PC
* LabVIEW version: 2020SP1
* MeasurementLink: Copied from main on 7/27/23
* InstrumentStudio: Built from main on 7/26/23

[AB#2469094](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2469094)

[AB#2900541](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2900541)

**Comment by bkeryan** [comment]
If we are passing LabVIEW strings directly to/from gRPC without converting between ANSI and UTF-8, this probably affects more than service registration (e.g. string configurations and outputs) and sounds like a grpc-labview bug.
