### ISSUE TITLE
Change location of Create Measurement Plug-In menu item

### ISSUE THREAD

**Issue by dixonjoel** [ni/measurement-plugin-labview#557]
# Bug Report

Should be at Tools >> Plug-In SDKs >> Measurement >> Create Measurement Plug-In...

## Your Environment

* OS & Device: Windows
* `ni-measurement-plugin-sdk-service` version 2.0.0.dev2

[AB#2791249](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2791249)

**Comment by ni-vsts-admins** [comment]
✅ Successfully linked to Azure Boards work item(s):
- [Bug 2791249](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2791249)
