### ISSUE TITLE
Can't delete #MeasurementToDo box in typedefs in Measurement Logic.vi

### ISSUE THREAD

**Issue by kirstyong** [ni/measurement-plugin-labview#560]
# Bug Report

v3.0.0.2 has bookmarks (#MeasurementToDo) for the measurement control and result typedefs that if deleted from the typedef, the measurement logic.vi does not update to show the removed green text box.

## Repro or Code Sample
Template that comes with the green bookmark in the typedef. This can be deleted. It is not recognized in bookmark manager.
![image](https://github.com/ni/measurement-plugin-labview/assets/134538964/687f9394-da95-4c51-90b2-3eeb99eafc4f)
Can't delete the green text box in measurement logic.vi
![image](https://github.com/ni/measurement-plugin-labview/assets/134538964/b08ba670-853b-4709-95b6-76f3ead4f66d)
MeasurementToDo is not being recognized (not bolded) in bookmark manager
![image](https://github.com/ni/measurement-plugin-labview/assets/134538964/7969c7b1-97aa-4ef4-96d9-15192cf2e1e9)

## Expected Behavior

Per past template versions, the green text box MeasurementToDo is supposed to just be a floating text box on the front panel that can be deleted when no longer needed.

## Current Behavior

If I delete the green bookmark from the typedef itself > apply changes > this does not apply the changes to the typedef in the measurement logic.vi. I have to add a new copy of the typedef to the logic.vi, delete the original, and that removes the green bookmark.

## Possible Solution

Maybe need to remove the green bookmark from the typedef itself....

## Your Environment

* OS & Device: Windows
* `ni-measurement-service` version 3.0.0.2
* IS Pro Pre-release d555 build
* LV 2024 Q1

[AB#2797761](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2797761)

**Comment by ni-vsts-admins** [comment]
✅ Successfully linked to Azure Boards work item(s):
- [Bug 2797761](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2797761)
