### ISSUE TITLE
LabVIEW Crash After Updating gRPC-LabVIEW Packages to Version 1.2.5.1

### ISSUE THREAD

**Issue by varshini-senthil** [ni/measurement-plugin-labview#594]
# Bug Report

LabVIEW crashes when running [`Enumerate Services.vi`](https://github.com/ni/measurement-plugin-labview/blob/main/Source/Runtime/Clients/Discovery%20V1/Enumerate%20Services.vi) under the Discovery client wrappers, with the update of gRPC LabVIEW package to version 1.2.5.1 from 1.0.1.1.

## Repro or Code Sample

- Install the packages provided in the latest release in our repo: [Measurement Plug-In SDK for LabVIEW 3.0.0.4](https://github.com/ni/measurement-plugin-labview/releases/tag/v3.0.0.4)
- Run the `Enumerate Services.vi` under the Discovery client wrapper library `NI Discovery V1 Client.lvlib` with default input
- LabVIEW crashes with the following error code:

![image](https://github.com/user-attachments/assets/39d7637c-83b9-40a1-9851-49a95ee544c1)

- Attached the generated error log for reference: [Error log](https://github.com/user-attachments/files/17032443/443b2e2c-6942-460e-bef0-42113f71323c.zip)
## Expected Behavior

The `Enumerate Services.vi` should run without issues and throw error if any invalid input arguments are provided.

## Current Behavior

The VI runs without error but causes LabVIEW crash after execution.

## Your Environment

* OS & Device: Windows 10
* Measurement Plug-In SDK Service version: 3.0.0.3
* LabVIEW version: 2021 SP1

[AB#2859207](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2859207)

**Comment by varshini-senthil** [comment]
This issue caused by the update of gRPC LabVIEW packages to version 1.2.5.1, affects the `Measurement Plug-In Client Generator` tool, as the Client generator uses the `Enumerate Services` API to get the list of available V2 measurement services.

cc: @dixonjoel @jasonmreding

**Comment by jasonmreding** [comment]
See https://github.com/ni/grpc-labview/issues/384.
